Fix for missing boot-settings.toml deprint: TTT
Did it this way cause I didn't want to propagate missing_ok all the way
to getSetting - fixes:

Traceback (most recent call last):
  File "D:\...\wrye-bash\Mopy\bash\ini_files.py", line 275, in read_ini_content
    with open(self.abs_path, mode='rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\***\\AppData\\Roaming\\WryeBash\\boot-settings.toml'